config/routes.rb
Rails.application.routes.draw do
  root to: "rooms#index"
  get "set_theme", to: "theme#update"

  resources :rooms, only: %i[ create index show ], param: :token do
    resources :messages, only: %i[ create show ]
  end

  mount ActionCable.server => "/cable"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room

  after_create_commit { broadcast_append_to self.room }
end

app/models/room.rb
class Room < ApplicationRecord
  before_create :generate_token
  after_create_commit { broadcast_append_to "rooms" }

  has_many :messages, dependent: :destroy

  def to_param
    token
  end

  private

  def generate_token
    self.token = SecureRandom.hex(2)
  end
end

app/models/user.rb
class User < ApplicationRecord
  before_create :generate_nickname

  has_many :messages, dependent: :destroy

  def still_connected?

    still_there = OnlineChannel.broadcast_to(self, action: 'presence-check')

    return true if still_there.is_a?(Integer) && still_there.positive?

    false
  end

  def set_offline
    Turbo::StreamsChannel.broadcast_remove_to("online_users", target: "user_#{self.id}")
  end

  private

  def generate_nickname
    self.nickname = Faker::Name.first_name.downcase
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user

  private

  def current_user
    @current_user ||= User.where(id: cookies.signed[:user_id]).first

    if @current_user.nil?
      @current_user = User.create
      cookies.signed[:user_id] = current_user.id
    end

    @current_user
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_room, only: %i[ create ]

  def create
    @new_message = @room.messages.build(msg_params)
    @new_message.user = current_user
    @new_message.save
  end

  private

  def msg_params
    params.require(:message).permit(:body)
  end

  def set_room
    @room = Room.find_by(:token => params[:room_token])
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: [:show]

  def index
    @rooms = Room.all
    @room = Room.new

    users_online = Kredis.unique_list "users_online"
    @users = User.find(users_online.elements)
  end

  def show
    @message = Message.new
    @messages = @room.messages
  end

  def create
    @room = Room.create!

    redirect_to @room, notice: 'Room was successfully created.'
  end

  private

  def set_room
    @room = Room.find_by(token: params[:token])
  end
end

app/controllers/theme_controller.rb
class ThemeController < ApplicationController
  def update
    cookies[:theme] = params[:theme]
    redirect_to(request.referrer || root_path)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Instachat</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body class="<%= cookies[:theme] %>">
    <%= turbo_stream_from "online_users", channel: OnlineChannel %>

    <div class="dropdown mx-2 mt-2">
      <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
        Color Scheme
      </button>
      <ul class="dropdown-menu">
        <li><a class="dropdown-item" href="<%= set_theme_path(theme: "light") %>"><i class="bi bi-circle"></i> Light</a></li>
        <li><a class="dropdown-item" href="<%= set_theme_path(theme: "dark") %>"><i class="bi bi-circle-fill"> Dark</i></a></li>
        <li><a class="dropdown-item" href="<%= set_theme_path %>"><i class="bi bi-circle-half"></i> Auto</a></li>
      </ul>
    </div>

    <div class="container">
      <div class="row justify-content-md-center">
        <div class="col-md-8">
          <div class="card text-center mt-4 mb-4">
            <div class="card-body rounded invite <%= cookies[:theme] %>">
              Welcome to Instatalk, <b><%= current_user.nickname %></b>!
            </div>
          </div>

          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/messages/_form.html.erb
<div class="form-group msg-form mt-2">
  <%= form_with(model: [@room, @message], remote: true, class: "d-flex",
                data: { controller: "reset", action: "turbo:submit-end->reset#reset" }) do |f| %>
    <%= f.text_field :body, id: 'chat-text', class: "form-control msg-content", autocomplete: 'off',
                     placeholder: 'Enter message' %>
    <%= f.submit data: { disable_with: false }, class: "btn btn-primary" %>
  <% end %>
</div>

app/views/messages/_message.html.erb
<div class="row message mt-1 justify-content-between">
  <div class="col-2 fw-bold text-info">
    <%= message.user.nickname %>
  </div>

  <div class="col-8 text-center">
    <p class="text-break"><%= message.body %></p>
  </div>

  <div class="col-2 text-end">
    <%= message.created_at.strftime("%H:%M") %>
  </div>
</div>

app/views/rooms/_form.html.erb
<%= form_for @room do |form| %>
  <div class="actions">
    <%= form.submit 'Create Room', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/rooms/_room.html.erb
<div><b>Room #<%= room.id %></b> — <%= link_to 'Join', room %></div>

app/views/rooms/index.html.erb
<h1>Users online</h1>
<div id="users-list">
  <% @users.each do |user| %>
    <%= render partial: "users/user", locals: { user: } %>
  <% end %>
</div>

<h1>Rooms</h1>

<%= turbo_stream_from "rooms" %>
<div id="rooms" class="mt-4 list-unstyled">
  <%= render @rooms %>
</div>

<div class="mt-2">
  <%= render 'rooms/form', room: @room %>
</div>

app/views/rooms/show.html.erb
<h1>Room <%= @room.id %></h1>

<%= link_to "Leave", root_path %>

<p id="notice"><%= notice %></p>

<div class="messages">
  <div class="messages-inner" id="messages" data-room-id="<%= @room.id %>" data-controller="scroll">
    <%= render @messages %>
  </div>
</div>

<%= turbo_stream_from @room %>
<%= render 'messages/form' %>

app/views/users/_user.html.erb
<div id="<%= dom_id(user) %>">
  <p class="fst-italic"><%= user.nickname %></p>
</div>